api:
  build: ./api
  working_dir: /src/
  command: "grunt serve"
  ports:
    - "3000:3000"
  volumes:
    - "./api:/src/api"
web:
  build: ./web
  working_dir: /src/
  command: "grunt serve"
  ports:
    - "9000:9000"
  volumes:
    - "./web:/src/web"