db:
  image: postgres
  ports:
    - "15432:5432"
  environment:
    POSTGRES_PASSWORD: docker
    POSTGRES_USER: docker
api:
  build: ./api
  working_dir: /src/
  command: "grunt serve"
  ports:
    - "3000:3000"
  volumes:
    - "./api:/src/api"
  links:
    - db
web:
  build: ./web
  working_dir: /src/
  command: "grunt serve"
  ports:
    - "9000:9000"
  volumes:
    - "./web:/src/web"